apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-slave
  lables:
    app: redis
spec:
  replicas: 3
  selector: 
    matchLables: 
      app: redis
      role: slave 
      tier: backend
template: 
  metadata: 
    labels:
      app: redis
      role: slave
      tier: backend
spec: 
  containers: 
  - name: redis-slave
    image: gcr.io/goolge_samples/gb-redisslave:v1
      resources: 
        requests: 
          cpu: 100m
          memory: 100Mi
  ports: 
  - containerPort:m 6379