apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  lables: 
    app: guestbook
    tier: frontend
spec: 
  selector: 
    matchLabels: 
      app: guestbook
      tier: frontend
  ports: 
  - port: 80
  type: LoadBalancer

          
